### ISSUE TITLE
Link for the toy dataset

### ISSUE THREAD

**Issue by rohitrango** [cq615/BIGM-motion-tracking#1]
Hi,

Thank you for releasing the code! The link to the toy dataset does not work. Could you share an alternative link?

**Comment by cq615** [comment]
> Hi,
> 
> Thank you for releasing the code! The link to the toy dataset does not work. Could you share an alternative link?

Hi, Please find the link here: https://www.creatis.insa-lyon.fr/Challenge/acdc/databases.html.
